### ISSUE TITLE
Use etag?

### ISSUE THREAD

**Issue by aquarhead** [ccpgames/esi-routes#1]
vague ideas: Generate data after etag change? after server deployed? instead of having to run `generate_data.py` separately and output to a json file.

**Comment by a-tal** [comment]
so far the universe layout has not changed. if it was going to change on some sort of frequent basis, yeah, sure. but until that frequency is real, and known, I don't see a reason to regenerate the data.

if we end up in a situation where the universe could be different day to day (and/or per datasource), we can look at generating data on app init, and cache using the existing universe etags.

**Comment by aquarhead** [comment]
Yeah, basically what I was thinking. More talking about the caching of routes can be etag'ed, and then that's related to how universe data is generated etc etc..

**Comment by a-tal** [comment]
tracked in ccpgames/esi-lib#130
